name: Go Fuzz Testing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  fuzz-ach:
    name: Fuzz ACH
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
      with:
        egress-policy: audit

    - name: Set up Go 1.x
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
        go-version: '>= 1.20.4'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        fetch-depth: 0

    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Fuzz
      run: |
        go test ./test/fuzz/... -fuzz ACH -fuzztime 10m

  fuzz-json:
    name: Fuzz JSON
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
      with:
        egress-policy: audit

    - name: Set up Go 1.x
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
        go-version: '>= 1.20.4'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        fetch-depth: 0

    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Fuzz
      run: |
        go test ./test/fuzz/... -fuzz JSON -fuzztime 10m
